// Dados extraídos da planilha "Cópia de DPROJ - DEMANDAS 02.2026.xlsx" (aba DEMANDAS)
// Total: 406 demandas | Extraído em 10/07/2026

const EMBEDDED_DATA = {
    "totalCount": 406,
    "highCount": 113,
    "normalCount": 173,
    "lowCount": 120,
    "campusMap": {
        "Samambaia": 220,
        "Colemar": 136,
        "Goiás": 9,
        "Não Definido": 17,
        "Firminópolis": 9,
        "Anápolis": 1,
        "Ap. Goiânia": 10,
        "Cidade Ocidental": 1,
        "Externo": 2,
        "Caldas Novas": 1
    },
    "unitMap": {
        "EVZ": 19,
        "FM": 13,
        "FF": 20,
        "GR": 7,
        "SEINFRA": 34,
        "FIRMINOPOLIS": 8,
        "BC": 5,
        "PROPESSOAS": 3,
        "FL": 14,
        "IQ": 16,
        "CEPAE": 4,
        "CGA": 4,
        "EA": 17,
        "DCF": 1,
        "IPTSP": 21,
        "SIN": 2,
        "ICB": 12,
        "DEC": 1,
        "Reitoria": 4,
        "IESA": 5,
        "PRAE": 15,
        "FD": 11,
        "FANUT": 3,
        "DASS": 5,
        "UAECSA-RG": 2,
        "FEN": 8,
        "PRPI": 13,
        "DIR-RG": 1,
        "FE": 9,
        "EMC": 13,
        "IME": 1,
        "SETI": 1,
        "CE": 3,
        "IF": 3,
        "Centro Cultural": 1,
        "FCT": 9,
        "HV": 1,
        "SECOM": 1,
        "DCOM": 3,
        "CEGRAF": 1,
        "Museu Antropológico": 1,
        "PTSS": 1,
        "NIPEE-DH": 1,
        "FIC": 6,
        "FCS": 2,
        "EECA": 3,
        "RG": 4,
        "FO": 5,
        "CEROF": 1,
        "INF": 6,
        "CIDARQ": 2,
        "ESTÁGIO": 1,
        "HC/EBSERH": 1,
        "FH": 5,
        "Herbário": 1,
        "EMAC": 2,
        "FEFD": 4,
        "FAV": 3,
        "PTS": 2,
        "Faculdade de Direito / DCOM": 1,
        "DLOG": 6,
        "SDH": 2,
        "PRPG": 2,
        "FACE": 1,
        "MUSEU": 2,
        "LAMES": 1,
        "SECPLAN": 1,
        "DAP": 2,
        "CIAR": 2,
        "Rádio Universitária": 1,
        "PROEC": 3,
        "SRI": 1,
        "PROEC - Centro de Eventos": 1,
        "DFP": 1,
        "UAECH-RG": 1,
        "PROGRAD": 2,
        "VD-CN": 1,
        "Instituto Verbena": 1,
        "CC": 1,
        "CDPA": 1,
        "CPA/EVZ": 1,
        "FEN/FANUT": 2,
        "CEPEA": 1,
        "CERCOMP": 1
    },
    "regionalMap": {
        "Goiânia": 378,
        "Goiás": 8,
        "Não Definida": 9,
        "Firminópolis": 9,
        "Cidade Ocidental": 1,
        "Caldas Novas": 1
    },
    "classificationMap": {
        "Reformas/Adequaçoes": 181,
        "Paisagismo": 36,
        "Regularização/Aprovação": 21,
        "Outros": 50,
        "Administrativo": 16,
        "Construções Novas": 29,
        "Estruturas de Apoio": 22,
        "Avaliação/Parecer/Estudo": 45,
        "Levantamento": 6
    },
    "yearMap": {
        "2026": 62,
        "2025": 71,
        "2024": 95,
        "2023": 91,
        "2022": 65,
        "2021": 13,
        "2020": 1,
        "2019": 5
    }
};

function getEmbeddedData() {
    return EMBEDDED_DATA;
}

window.EMBEDDED_DATA = EMBEDDED_DATA;