// Dados extraídos da planilha "Cópia de DPROJ - DEMANDAS 02.2026.xlsx" (aba DEMANDAS)
// Total: 406 demandas | Extraído em 10/07/2026

const EMBEDDED_DATA = {
    "totalCount": 406,
    "highCount": 113,
    "normalCount": 173,
    "lowCount": 120,
    "campusMap": {
        "Samambaia": 220,
        "Colemar": 136,
        "Goiás": 9,
        "Não Definido": 17,
        "Firminópolis": 9,
        "Anápolis": 1,
        "Ap. Goiânia": 10,
        "Cidade Ocidental": 1,
        "Externo": 2,
        "Caldas Novas": 1
    },
    "unitMap": {
        "EVZ": 19,
        "FM": 13,
        "FF": 20,
        "GR": 7,
        "SEINFRA": 34,
        "FIRMINOPOLIS": 8,
        "BC": 5,
        "PROPESSOAS": 3,
        "FL": 14,
        "IQ": 16,
        "CEPAE": 4,
        "CGA": 4,
        "EA": 17,
        "DCF": 1,
        "IPTSP": 21,
        "SIN": 2,
        "ICB": 12,
        "DEC": 1,
        "Reitoria": 4,
        "IESA": 5,
        "PRAE": 15,
        "FD": 11,
        "FANUT": 3,
        "DASS": 5,
        "UAECSA-RG": 2,
        "FEN": 8,
        "PRPI": 13,
        "DIR-RG": 1,
        "FE": 9,
        "EMC": 13,
        "IME": 1,
        "SETI": 1,
        "CE": 3,
        "IF": 3,
        "Centro Cultural": 1,
        "FCT": 9,
        "HV": 1,
        "SECOM": 1,
        "DCOM": 3,
        "CEGRAF": 1,
        "Museu Antropológico": 1,
        "PTSS": 1,
        "NIPEE-DH": 1,
        "FIC": 6,
        "FCS": 2,
        "EECA": 3,
        "RG": 4,
        "FO": 5,
        "CEROF": 1,
        "INF": 6,
        "CIDARQ": 2,
        "ESTÁGIO": 1,
        "HC/EBSERH": 1,
        "FH": 5,
        "Herbário": 1,
        "EMAC": 2,
        "FEFD": 4,
        "FAV": 3,
        "PTS": 2,
        "Faculdade de Direito / DCOM": 1,
        "DLOG": 6,
        "SDH": 2,
        "PRPG": 2,
        "FACE": 1,
        "MUSEU": 2,
        "LAMES": 1,
        "SECPLAN": 1,
        "DAP": 2,
        "CIAR": 2,
        "Rádio Universitária": 1,
        "PROEC": 3,
        "SRI": 1,
        "PROEC - Centro de Eventos": 1,
        "DFP": 1,
        "UAECH-RG": 1,
        "PROGRAD": 2,
        "VD-CN": 1,
        "Instituto Verbena": 1,
        "CC": 1,
        "CDPA": 1,
        "CPA/EVZ": 1,
        "FEN/FANUT": 2,
        "CEPEA": 1,
        "CERCOMP": 1
    },
    "regionalMap": {
        "Goiânia": 378,
        "Goiás": 8,
        "Não Definida": 9,
        "Firminópolis": 9,
        "Cidade Ocidental": 1,
        "Caldas Novas": 1
    },
    "classificationMap": {
        "Reformas/Adequaçoes": 181,
        "Paisagismo": 36,
        "Regularização/Aprovação": 21,
        "Outros": 50,
        "Administrativo": 16,
        "Construções Novas": 29,
        "Estruturas de Apoio": 22,
        "Avaliação/Parecer/Estudo": 45,
        "Levantamento": 6
    },
    "yearMap": {
        "2026": 62,
        "2025": 71,
        "2024": 95,
        "2023": 91,
        "2022": 65,
        "2021": 13,
        "2020": 1,
        "2019": 5
    },
    "data2026": {
        "totalCount": 62,
        "highCount": 21,
        "normalCount": 18,
        "lowCount": 23,
        "campusMap": {
            "Samambaia": 27,
            "Colemar": 22,
            "Firminópolis": 7,
            "Goiás": 3,
            "Não Definido": 3
        },
        "unitMap": {
            "FM": 7,
            "FIRMINOPOLIS": 7,
            "SEINFRA": 4,
            "EVZ": 3,
            "FL": 3,
            "IQ": 3,
            "FD": 3,
            "FF": 2,
            "GR": 2,
            "PROPESSOAS": 2,
            "CEPAE": 2,
            "EA": 2,
            "IPTSP": 2,
            "SIN": 2,
            "ICB": 2,
            "IESA": 2,
            "PRAE": 2,
            "BC": 1,
            "CGA": 1,
            "DCF": 1,
            "DEC": 1,
            "Reitoria": 1,
            "FANUT": 1,
            "DASS": 1,
            "UAECSA-RG": 1,
            "FEN": 1,
            "PRPI": 1,
            "DIR-RG": 1,
            "FE": 1
        },
        "regionalMap": {
            "Goiânia": 49,
            "Goiás": 3,
            "Não Definida": 3,
            "Firminópolis": 7
        },
        "classificationMap": {
            "Reformas/Adequaçoes": 32,
            "Paisagismo": 6,
            "Regularização/Aprovação": 2,
            "Outros": 7,
            "Administrativo": 4,
            "Construções Novas": 8,
            "Estruturas de Apoio": 2,
            "Avaliação/Parecer/Estudo": 1
        }
    },
    "completedMap": {
        "2022": 35,
        "2023": 62,
        "2024": 63,
        "2025": 68,
        "2026": 45
    }
};

function getEmbeddedData() {
    return EMBEDDED_DATA;
}

window.EMBEDDED_DATA = EMBEDDED_DATA;